### ISSUE TITLE
Error when launching map on spring

### ISSUE THREAD

**Issue by TurBoss** [Beherith/springrts_smf_compiler#3]
Hi

I'm trying to compile a map in linux and I found that spring crashes when tries to load it

here is the infolog.txt

http://paste.springfiles.com/view/190f4212

the map has a size of 16x12 and no features yet

thank you

**Comment by Beherith** [comment]
Could you please paste the output of pymapconv?
Ill look into why it seems like it added a blank feature as well.
"[f=-000001] Error: [LoadFeatureDefsFromMap] unknown map feature type ""
[f=-000001] Error: [LoadFeatureDefsFromMap] unknown map feature type "" *10k

[f=-000001] Error: [GetFeatureDef] could not find FeatureDef """

**Comment by TurBoss** [comment]
here is the output

http://paste.springfiles.com/view/94d6254f

**Comment by Beherith** [comment]
A quick easy test would be to decompile the same map with pymapconv, and see if the texture is corrupted.

**Comment by TurBoss** [comment]
this is the output of trying to decompile the smf
http://paste.springfiles.com/view/8e040c88

**Comment by Beherith** [comment]
Ok, so I'm pretty sure the is caused by the difference of how imagemagick and nvdxt interpret the number of mipmaps to be generated, and one is off by 1. My headless linux wont allow the running of this cause of the QTGui :( 
"len minimapdata 699056 of 699048"
is a hint that there is 1 more mip level than there should be, or that the headers are somehow different.

**Comment by Beherith** [comment]
Ok i fixed headless, but my old version of imagemagick on my linuxbox doesnt support DDS

**Comment by Beherith** [comment]
Should be fixed now, can you give it a nother go?

**Comment by TurBoss** [comment]
yahoo its fixed thank you so much!!
